<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ACProfiles extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $nice = [
            ["user_id"=>"2","fullname"=>"Admin - simrsku.com","avatar"=>"UAZNub4Xt4rA0LRGvDKFXkkHjp95DmQMF3rE5k3n.jpg","status"=>"1"],
            ["user_id"=>"4","fullname"=>"jamhuri - kabag-keperawatan","avatar"=>"NuYb1dWqQPifpGoz0ucXEerUvjng49LqXtdCwcKS.jpg","status"=>"1"],
            ["user_id"=>"6","fullname"=>"intan - bangsal-anak","avatar"=>"vEPzZVcAh7PA6M88BFMdHClG1EB1nKIb7u9eLdTi.jpg","status"=>"1"],
            ["user_id"=>"8","fullname"=>"afidah - ibs","avatar"=>"EbO8Zp8cJQNwQuUkWSX0CcuhDHWzuGv4WazryzkG.jpg","status"=>"1"],
            ["user_id"=>"9","fullname"=>"srinur - igd","avatar"=>"idvzp0SeOvzvv35Vki8WLf7ssU0Db9SCRNL9gmR5.jpg","status"=>"1"],
            ["user_id"=>"10","fullname"=>"anigalihr - bangsal-anak","avatar"=>"lEqB99WQtM9UxNWNlX5z3O3pLiis29JP1XzKTSwU.jpg","status"=>"1"],
            ["user_id"=>"11","fullname"=>"yanadp - bangsal-anak","avatar"=>"YBjInNV2rn9yyAtRb9NEFEVSdP0j3WbaA9EI9ccL.jpg","status"=>"1"],
            ["user_id"=>"15","fullname"=>"pika - bangsal-dewasa","avatar"=>"6xVSPToqfHV0XBllIK6W7KU6RBAOI03suSD4LDq9.jpg","status"=>"1"],
            ["user_id"=>"17","fullname"=>"rohmad - icu","avatar"=>"xvjS7q96Gqvf1OlTKujr0FF0keLn1MVctaccsbbV.jpg","status"=>"1"],
            ["user_id"=>"18","fullname"=>"ita - bangsal-anak","avatar"=>"IhiXmU4bH1HlEC4ZjF8lwKcsjoYumqgtGP2zdwUL.jpg","status"=>"1"],
            ["user_id"=>"21","fullname"=>"handayani - ibs","avatar"=>"ORlKh55UHCUweyWvtfMcVgrtSG6C3A8XQbaaETT4.jpg","status"=>"1"],
            ["user_id"=>"22","fullname"=>"yoga - icu","avatar"=>"hlinrzD2yGJwQXDW63hw7TRkF4bPmUKQ42RRDEUL.jpg","status"=>"1"],
            ["user_id"=>"24","fullname"=>"muyas - bangsal-anak","avatar"=>"h02YA4tuZg232KgGDaqQuR4CGItkrfhxeC9OsWp2.jpg","status"=>"1"],
            ["user_id"=>"25","fullname"=>"prita - icu","avatar"=>"tTQDDgeNSh3bq88Sa0v5U3bBMlIxP0PJOVlbXoF8.jpg","status"=>"1"],
            ["user_id"=>"26","fullname"=>"narif - igd","avatar"=>"I9hNXG2dAGGUkNASfSncedwlolc34BXJMyVuB2Y0.jpg","status"=>"1"],
            ["user_id"=>"28","fullname"=>"fitri - igd","avatar"=>"auUfyOZAjTU8Fj4sc4VAFbcRQbBrYkOQxyMnfXgS.jpg","status"=>"1"],
            ["user_id"=>"30","fullname"=>"selfi - icu","avatar"=>"IF6ArHNnErJp4DF3sqxpV5Eq5S7CuBMDbtM2fRze.jpg","status"=>"1"],
            ["user_id"=>"34","fullname"=>"dewi - bangsal-dewasa","avatar"=>"I60qLxz9lbMIA3P4m1nGys7DJTvLuGWtrihCQ4iF.jpg","status"=>"1"],
            ["user_id"=>"36","fullname"=>"neny - icu","avatar"=>"VN9P4Ex1ts49agKxOwWRE5GNZBL4XZ2RIC1oxK2X.jpg","status"=>"1"],
            ["user_id"=>"38","fullname"=>"ipoet - icu","avatar"=>"O9xNAITCk557oEgvXYV9OAeT9Z5M5GXJ3ZPSM9ln.jpg","status"=>"1"],
            ["user_id"=>"40","fullname"=>"tian - igd","avatar"=>"n5BcjnkPen0WKs8GWFbgIg2WYmBuDF0SmfEHoO0C.jpg","status"=>"1"],
            ["user_id"=>"45","fullname"=>"adik - ibs","avatar"=>"G0oalpXmal9MgswQmJppY4WHm5Of7L0lSJ9904DL.jpg","status"=>"1"],
            ["user_id"=>"46","fullname"=>"ningsih - ibs","avatar"=>"pmgTZFpAwDnf35ltPztMkxRXkvdkuXC2vRAUOpXX.jpg","status"=>"1"],
            ["user_id"=>"47","fullname"=>"whawan - k3","avatar"=>"vuaUOLUXHWy7e1CpARJYGIxxzQAiCSN2L8jpXWrI.jpg","status"=>"1"],
            ["user_id"=>"49","fullname"=>"pungky - bangsal-dewasa","avatar"=>"rX9EqYhnEK9DPapH2IUzzSU4zt8hPdyg6zHazYCj.jpg","status"=>"1"],
            ["user_id"=>"52","fullname"=>"yogaisma - igd","avatar"=>"GahC7T73nXylXyPKlolWMXiBjCrLfI0hU1kml1o3.jpg","status"=>"1"],
            ["user_id"=>"53","fullname"=>"rahmat - bangsal-dewasa","avatar"=>"aTsRr1tKUaviZ0j6umAjfvK1NtJKoNwikB18X4mv.jpg","status"=>"1"],
            ["user_id"=>"54","fullname"=>"andiari - ibs","avatar"=>"ntBG0u9MOVryQ2dK07MjLEMUnNvrJ8LZbopDJlWu.jpg","status"=>"1"],
            ["user_id"=>"56","fullname"=>"bagus - icu","avatar"=>"BfJ5bjaqxMT66iSroWB4zvR9vXqlMLTyncEtWap0.jpg","status"=>"1"],
            ["user_id"=>"58","fullname"=>"pangesthika - igd","avatar"=>"lBdz2j4gxx8OoYAYI8iGwDSp1Vc2sMHmgwBMmomz.jpg","status"=>"1"],
            ["user_id"=>"61","fullname"=>"darwanto - igd","avatar"=>"1OFnhZ2jLCs7UmAnxy5Kl6liRYnvLl9N9A7B2Vwk.jpg","status"=>"1"],
            ["user_id"=>"62","fullname"=>"danar - igd","avatar"=>"0zQ3TiwylxlAwj6sTGapCp8q3XFjj0QvF37OQ3rb.jpg","status"=>"1"],
            ["user_id"=>"64","fullname"=>"ari - igd","avatar"=>"7VMUi1X8jsTkqHvKbcJeaQoxTBYfJ1APmvCjZVqB.jpg","status"=>"1"],
            ["user_id"=>"65","fullname"=>"weni - kebidanan","avatar"=>"4Ppe09JJ68u7kCoWCF1eSc0LRQNVl974U76i91YA.jpg","status"=>"1"],
            ["user_id"=>"66","fullname"=>"rini - kebidanan","avatar"=>"5irpHM6gJZP3t4sAUJ1w5a5yDcg8NTmNZd4dBgUt.jpg","status"=>"1"],
            ["user_id"=>"67","fullname"=>"ulil - kebidanan","avatar"=>"1jQNpiYdEsrOToq6zPpuXLWem9bUgKwiMs42JhRo.jpg","status"=>"1"],
            ["user_id"=>"68","fullname"=>"yessy.ek - kebidanan","avatar"=>"mrqsKrZzXKHgxQ7kq4g5ZhnvRjiDHSvdUZz3odKs.jpg","status"=>"1"],
            ["user_id"=>"69","fullname"=>"titi - kebidanan","avatar"=>"3VeJPFQEJNXvBlneyOh2ZfH8oxzgVjFFLn8B7jDf.jpg","status"=>"1"],
            ["user_id"=>"70","fullname"=>"nurulafida - kebidanan","avatar"=>"HbpFPUB7HW27yWWsLu49rwoTmrQSOykSJWWqEdoR.jpg","status"=>"1"],
            ["user_id"=>"73","fullname"=>"chandra - kebidanan","avatar"=>"mrqOGwRuWysRjZqYeNCVf8Yx9jZlYNIKjo8mBrkM.jpg","status"=>"1"],
            ["user_id"=>"74","fullname"=>"siska - kebidanan","avatar"=>"uRsOpPXjm74fSwntXGbpKQK9tPLnFoH5ufKr2ZYj.jpg","status"=>"1"],
            ["user_id"=>"77","fullname"=>"nisa - kebidanan","avatar"=>"Fxn0myN9MXgNRUXtmGD2Fd0YN0dKxHPIO65KCz1r.jpg","status"=>"1"],
            ["user_id"=>"79","fullname"=>"etik - poli","avatar"=>"bt4MAs2PXsRdxXqZjiZFy9u4VXnGWkC5ojlVukW3.jpg","status"=>"1"],
            ["user_id"=>"94","fullname"=>"fajar - staf-keuangan","avatar"=>"35dgT9bAJaG8qRNfyG2ImfRG5JROgJMfFi4hvAIM.jpg","status"=>"1"],
            ["user_id"=>"100","fullname"=>"sriyono - ipsrs","avatar"=>"9BAYvWgLLTFb8palvZ46OHzhArb9zQndfnSEA2aw.jpg","status"=>"1"],
            ["user_id"=>"102","fullname"=>"novita - pmkp","avatar"=>"LKDTBYWuxZNKciAlYI8ABxVK4I5flNZLgmhQDcze.jpg","status"=>"1"],
            ["user_id"=>"104","fullname"=>"meytyas - pkrs","avatar"=>"jbgQ5oegvwWew8ktKQl8spOIj8LRbrzKg9u53U7X.jpg","status"=>"1"],
            ["user_id"=>"105","fullname"=>"nopita - ppi","avatar"=>"jmVA4IvkPJ0j6ql57wbLwaBdxwlPbG6MfRWBRpg8.jpg","status"=>"1"],
            ["user_id"=>"107","fullname"=>"uut - spv","avatar"=>"p9qpCNFYJOSKU1Ver6038F45HSMVNsfTrXtRtN88.jpg","status"=>"1"],
            ["user_id"=>"108","fullname"=>"lasmi - farmasi","avatar"=>"uPdif9VMUBzGy3QhYX5khIn9R83A0cl53lrOjoxt.jpg","status"=>"1"],
            ["user_id"=>"110","fullname"=>"rachma - farmasi","avatar"=>"8iFlo9ch7RnUeYbO05LP7eT8Ja34jQrQRFNGWzRv.jpg","status"=>"1"],
            ["user_id"=>"111","fullname"=>"tri - farmasi","avatar"=>"Lp6fp9N6vdehwjvo7RanUAwoHGMLyDh1H7iUmD8g.jpg","status"=>"1"],
            ["user_id"=>"113","fullname"=>"vivit - farmasi","avatar"=>"8no3jCTFfbS5kHPTqEIpVsEwz787JqMZgBHPSQra.jpg","status"=>"1"],
            ["user_id"=>"116","fullname"=>"yuli - farmasi","avatar"=>"pGaD4Z1AqXpJ4TK2SBtUs1udXZN7xpcWDzjY4PZz.jpg","status"=>"1"],
            ["user_id"=>"118","fullname"=>"imel - farmasi","avatar"=>"chrEvYP1EckcoNwmZDkPTKfrdZCjf299ta04y5vX.jpg","status"=>"1"],
            ["user_id"=>"119","fullname"=>"windy - farmasi","avatar"=>"G9ybkKSElM4jGBOnN4QbFKjPGk51luZTd7EQQb8d.jpg","status"=>"1"],
            ["user_id"=>"121","fullname"=>"bambang - farmasi","avatar"=>"EDRbdFJ3R0kHVxbHBvzdpl2va2dMPhyVzAqqrqQX.jpg","status"=>"1"],
            ["user_id"=>"122","fullname"=>"ningsih - farmasi","avatar"=>"7H70sivGoWA6G5gik5XVcLYPbOYhXu5ZNm4Es7dj.jpg","status"=>"1"],
            ["user_id"=>"123","fullname"=>"nita - rm","avatar"=>"KrwXZR6laqW3unHEqLrXjWRKOsQ4XDpro87AdPSB.jpg","status"=>"1"],
            ["user_id"=>"124","fullname"=>"titin - rm","avatar"=>"ZDT2D8lisTJOBulps5vktQpx3sPyJQdmjKzzo9Gj.jpg","status"=>"1"],
            ["user_id"=>"125","fullname"=>"annisa - rm","avatar"=>"Of9PNT1JBfrtfirUi33IvbwQV1SGyKHeKJsTd2O5.jpg","status"=>"1"],
            ["user_id"=>"126","fullname"=>"syaroh - rm","avatar"=>"PiPcQKln4UHrsy7Cb2mVC8QFENHBKBTM8tCOmAbn.jpg","status"=>"1"],
            ["user_id"=>"129","fullname"=>"ima - rm","avatar"=>"WCrjXB02ttJvXAV66wk6VhoQj0MBtXq9skV1ky59.jpg","status"=>"1"],
            ["user_id"=>"130","fullname"=>"dafi - rm","avatar"=>"uByGUTztti5jfdr4K6HrtWZEBdJR0MSnkUKRWrqf.jpg","status"=>"1"],
            ["user_id"=>"131","fullname"=>"anik - rm","avatar"=>"UVNiWJrKs77Fx3EdvfmAWYDvlm5e2mNHEWBBxylv.jpg","status"=>"1"],
            ["user_id"=>"132","fullname"=>"asyah - rm","avatar"=>"oHMf5ATCDJHizg43BORfG68vViFaGunK5KHyeorI.jpg","status"=>"1"],
            ["user_id"=>"133","fullname"=>"syafira - rm","avatar"=>"qnc3Ob4VRXNFxm8c98CbFLRf7BVKMWt9Bh5tIwvD.jpg","status"=>"1"],
            ["user_id"=>"135","fullname"=>"sasa - gizi","avatar"=>"h7y1axGMbW7VcnlNDNcAzqB4RYxmncOABK0H6xOd.jpg","status"=>"1"],
            ["user_id"=>"136","fullname"=>"desi - gizi","avatar"=>"VAtAa4ONJjjqRdaDPDSlDeBSYFuFsQSGVvwcuwlW.jpg","status"=>"1"],
            ["user_id"=>"138","fullname"=>"evi - gizi","avatar"=>"uu9pIjb342uhFYlCudgCORAu9LorkUfNF5ev1Id2.jpg","status"=>"1"],
            ["user_id"=>"144","fullname"=>"siti - gizi","avatar"=>"c78c9cEpnMoxpNDIJU73t1WGUGHSBR5v1meVtSlg.jpg","status"=>"1"],
            ["user_id"=>"146","fullname"=>"guntur - rehabilitasi-medik","avatar"=>"CjJwJ7CWI597UDFexE2SAbZ8AH4t7nHvkampTV5p.jpg","status"=>"1"],
            ["user_id"=>"150","fullname"=>"lilis - lab","avatar"=>"fW2ggWLFC7PIExYWrbSNTU1NTtDT9srm8Lq53w9O.jpg","status"=>"1"],
            ["user_id"=>"151","fullname"=>"ratna - lab","avatar"=>"oNiRgpwjqcqgCeI8wxlvSsAuzui5w1lLBprT3c4S.jpg","status"=>"1"],
            ["user_id"=>"154","fullname"=>"wahyunugroho - lab","avatar"=>"jpoheyuMnBzncPWtXC5nvDRjwj3wEJ4vp6nfN6ZL.jpg","status"=>"1"],
            ["user_id"=>"155","fullname"=>"vita - lab","avatar"=>"2wjYz4bKZ1U2S64G7FaF9XX6TWuelo7xnYEvvLce.jpg","status"=>"1"],
            ["user_id"=>"157","fullname"=>"murtini - cssd","avatar"=>"fxTD6REOfMmB5a1Iu4502WYOSoUbgTknSpp51O4G.jpg","status"=>"1"],
            ["user_id"=>"158","fullname"=>"melon - cssd","avatar"=>"7Aw90W6iehsE8FUM1kmlHND5oZryTZPTylkLnFKo.jpg","status"=>"1"],
            ["user_id"=>"167","fullname"=>"panggih - cs","avatar"=>"WNPI4xaeyMCQLBomTiiaySW9XPBmrf6Vlm9bhHIm.jpg","status"=>"1"],
            ["user_id"=>"169","fullname"=>"joko - cs","avatar"=>"n8HjYFAvRiDvSp9frSBdoFgW7OPDSK3CHxwUMJ4S.jpg","status"=>"1"],
            ["user_id"=>"170","fullname"=>"andi - cs","avatar"=>"xOhNSGoScFEzDoggrhEdnTpn8Oqkq6tQJNuYLTZS.jpg","status"=>"1"],
            ["user_id"=>"172","fullname"=>"supri - cs","avatar"=>"DgwUAzLaPFIu09lZTqj0mU9SxCA09StqQQxvx6Zp.jpg","status"=>"1"],
            ["user_id"=>"174","fullname"=>"dedik - cs","avatar"=>"WQQXROo4f1Df6vnB9Db3dh4IWtW1z4MOBSLQBR1v.jpg","status"=>"1"],
            ["user_id"=>"175","fullname"=>"anggoro - cs","avatar"=>"MVHecVZjRZYTCR7WBCA8ytTqyJ9ZSdiW90XHiPos.jpg","status"=>"1"],
            ["user_id"=>"180","fullname"=>"aribolang - security","avatar"=>"mT2hkKFzrTYxxeazmYsKUYeUdashrAVnxNXS2RpD.jpg","status"=>"1"],
            ["user_id"=>"181","fullname"=>"kris - security","avatar"=>"IV16NHu6vT871oHR6hTXw7CZjX3LSNkvfbP7QTvT.jpg","status"=>"1"],
            ["user_id"=>"186","fullname"=>"endang - kasir","avatar"=>"B4xDJsegSOswe3HRynVfuC0P6NdrxwybErfjWAQ2.jpg","status"=>"1"],
            ["user_id"=>"189","fullname"=>"mamad - kasir","avatar"=>"gw4YCDMxzCCYAeHMU7aTSNlNjb4XiVDIGOHoa0sy.jpg","status"=>"1"],
            ["user_id"=>"191","fullname"=>"srimaryanti - laundry","avatar"=>"3NXBcMYm3lxNWU4idAxM9HTObS3w2jiVF8lVE3XR.jpg","status"=>"1"],
            ["user_id"=>"192","fullname"=>"usman - laundry","avatar"=>"a1UEeXnxZh70IRN6lJMOBW8iSyflBTIS2D1z7bTX.jpg","status"=>"1"],
            ["user_id"=>"193","fullname"=>"dwisusi - laundry","avatar"=>"ce4dVs5MtlFYg4olmr7gm0IhkB6D1MF2q3FEqFiV.jpg","status"=>"1"],
            ["user_id"=>"194","fullname"=>"adi - laundry","avatar"=>"3t9Cxh1GrYoFYpAnP9lo8tTy6bxhaRz8I7aLZTc2.jpg","status"=>"1"],
            ["user_id"=>"195","fullname"=>"hariyanto - driver","avatar"=>"RLp0ZweWCcua0A9THJSPpRhjzMcHq6NCvcqPtKzf.jpg","status"=>"1"],
            ["user_id"=>"197","fullname"=>"suroyo - driver","avatar"=>"0e4NuLm9sSMbyxdcv5Yn2NCc50cM3rWRAz1jrjEx.jpg","status"=>"1"],
            ["user_id"=>"198","fullname"=>"rais - driver","avatar"=>"loY5wjBRa1fEjUP4awjAl4IThcxEyo62uQYYEhTd.jpg","status"=>"1"],
            ["user_id"=>"200","fullname"=>"andriyah - gizi","avatar"=>"n1gN8ssmn69Xb1W9eSygm6IN9Cb5gzpQqTRmMJYh.jpg","status"=>"1"],
            ["user_id"=>"201","fullname"=>"yogi - bangsal-dewasa","avatar"=>"pjym8NlidV8EZbzbQWmrL2jQTJ2G9k1vF2WEEaOw.jpg","status"=>"1"],
            ["user_id"=>"202","fullname"=>"andisetiawan - bangsal-anak","avatar"=>"NgpoL8SVKf7GaGMt1xP73gPf0N8slXxSSfJH1YMi.jpg","status"=>"1"],
            ["user_id"=>"203","fullname"=>"dessy - bangsal-dewasa","avatar"=>"CeahHyzLCh2KazL59kGRhnrjvpOrKaFFe0K0iNK8.png","status"=>"1"],
            ["user_id"=>"207","fullname"=>"tyas - rm","avatar"=>"11ylV9IMlXx6LEZiQTbXn5XpmyanxGPZUkPDwpZi.jpg","status"=>"1"],
            ["user_id"=>"208","fullname"=>"faqih - rm","avatar"=>"CFiF7bce5GbbpqW7tJyvbdvxBocLxtEbrC3oWEl9.jpg","status"=>"1"],
            ["user_id"=>"211","fullname"=>"aris - bangsal-dewasa","avatar"=>"D21R6GRAD61UDpugGiJNBKnomCLelqroHHuXERKk.jpg","status"=>"1"],
            ["user_id"=>"212","fullname"=>"dania - icu","avatar"=>"1zaSQ13eWCRK0ed66isRNghi94gSZ7OPTrQ3IwY5.jpg","status"=>"1"],
            ["user_id"=>"213","fullname"=>"kusnandar - ibs","avatar"=>"Kf8cnduh13HJ3rf0C9GKJzhQtNZYDieJEUmO6AyL.jpg","status"=>"1"],
            ["user_id"=>"218","fullname"=>"suwarti - bangsal-anak","avatar"=>"3CN6JZfEjsxkjod64TfHuC2M0g9o3KSWPyPcWyo2.jpg","status"=>"1"],
            ["user_id"=>"219","fullname"=>"anggi - bangsal-dewasa","avatar"=>"OeKvdZxkos6A5s4MiEJAvMOmyNgHqd0BIdjOkdbD.jpg","status"=>"1"],
            ["user_id"=>"220","fullname"=>"dimasbangsal - bangsal-dewasa","avatar"=>"LGtoEN2O6dLXkUWsnCkC07SjYk5B4zXmsLZPcQgH.jpg","status"=>"1"],
            ["user_id"=>"221","fullname"=>"fajartri - bangsal-dewasa","avatar"=>"NhCNXmMzAh3pKU3KTtZCWpXlZATkipqi4WnUbNc0.jpg","status"=>"1"],
            ["user_id"=>"222","fullname"=>"hanif - poli","avatar"=>"ZJyOrdKgOvdnRsBbXQshZ3vY8vwrBHsK5O6i6ztE.jpg","status"=>"1"],
            ["user_id"=>"225","fullname"=>"Ryskenprima - bangsal-dewasa","avatar"=>"9ADtrGRfNJThh6u7mijDsgLPhKs35B47ocT2wVJe.jpg","status"=>"1"],
            ["user_id"=>"230","fullname"=>"ryandika - pelayanan","avatar"=>"Y13gMLdQd6pY5k5y0q9zrGIl7f5WAfKMePKa0nx6.jpg","status"=>"1"],
            ["user_id"=>"232","fullname"=>"yussuffaisal - it","avatar"=>"qBQheZzO79ISXG6SI8VQIaA0CJtTMTJqee26IAtk.jpg","status"=>"1"],
            ["user_id"=>"233","fullname"=>"rizal - it","avatar"=>"znVjfK5MKn5esbeOcslcqRPzFqhky9QsYqoygOYP.png","status"=>"1"],
            ["user_id"=>"235","fullname"=>"fariz - kantor","avatar"=>"6yPD8Z4PUPHQhtNdvGsZMppGHzXzDFR7wcoBHuxw.jpg","status"=>"1"],
            ["user_id"=>"236","fullname"=>"pipit - kantor","avatar"=>"bnBMm52S45mKcgNF69aerqJoCHYatTVYY7VbDmdO.jpg","status"=>"1"],
            ["user_id"=>"237","fullname"=>"qomsiyah - poli","avatar"=>"6hCo22hBbYDCGpK1yJQ3spfSamTbzzFIgqnsXRP2.jpg","status"=>"1"],
            ["user_id"=>"238","fullname"=>"murti - spv","avatar"=>"E7UPXvNWX47Oj7FbsvrkdIz3X7we5sgThBQK5Iid.jpg","status"=>"1"],
            ["user_id"=>"239","fullname"=>"nday - spv","avatar"=>"v000T7zM8cZkNgwKhVKswt1H5Vx9RboT3cAtvmEL.jpg","status"=>"1"],
            ["user_id"=>"240","fullname"=>"srilestari - bangsal-anak","avatar"=>"tcHNVLQZ32aJwuQhzUaXiXC0HhHbtmVtLatMl5bp.jpg","status"=>"1"],
            ["user_id"=>"241","fullname"=>"fatkhul - ipsrs","avatar"=>"yNX84evHJ99iPFRFesyiS3v6VGOQAH28TmVGJjTO.jpg","status"=>"1"],
            ["user_id"=>"243","fullname"=>"zulaikha - it","avatar"=>"UEUnEejP7WZyeZCu0lTiQDxrzR0wGK48hUAYBnt5.jpg","status"=>"1"],
            ["user_id"=>"245","fullname"=>"ahmadi - cssd","avatar"=>"24D5Nag2CIttjiUu2jkHgxMRfiow6wyrheoVljsB.jpg","status"=>"1"],
            ["user_id"=>"249","fullname"=>"dzaky - kantor","avatar"=>"quycsacHJpU3pUMiYA6A9ZHqESre8hffDbQLOq1F.png","status"=>"1"],
            ["user_id"=>"252","fullname"=>"rafida - fulltimer","avatar"=>"tuj92jI42AKCNLhbLdmPAUcOq0Gb2XU7ppSBATAI.jpg","status"=>"1"],
            ["user_id"=>"253","fullname"=>"fitriana - fulltimer","avatar"=>"EcxdTGjSDftbFfqCsdpXRuFkl6kRVBmivULr1iD7.jpg","status"=>"1"],
            ["user_id"=>"258","fullname"=>"septian - cs","avatar"=>"eQLG8EpJpSQqzsTZ1NS2A5YUKdeiCyx4EV4wSVtF.jpg","status"=>"1"],  
        ]; 
        DB::table('ac_profiles')->insert($nice);
    }
}
